# Generated by Django 5.0.1 on 2024-03-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(verbose_name=12),
        ),
    ]
