# Generated by Django 5.0.1 on 2024-03-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0005_alter_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
