# Generated by Django 5.0.1 on 2024-03-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0006_alter_appointment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='pt_name',
        ),
    ]
