# Generated by Django 5.0.1 on 2024-03-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0007_rename_name_appointment_pt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pt_name',
            new_name='name',
        ),
    ]
