# Generated by Django 5.0.1 on 2024-03-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0008_rename_pt_name_appointment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='pt_name',
        ),
    ]
